Completed Active Connector Skill Test
activeconnector/ac-test pull request #9
Opened 2022-09-09 02:35 UTC by abaeg

## Questionnaire

- Where did you find the job? -> LinkedIn / Indeed / Kyujin Box / Referral
- Have you applied on the site above? -> Yes / No

## Agreement

- [ ] I did not ask anyone for help to solve the problem.
- [ ] I did not refer any other forks or pull requests of this repository.
- [ ] I would make my fork private if requested after screening.

2022-09-12 06:49 UTC, hasundue commented
Thank you, this is an interesting solution!
Do you think it what we expected?

2022-09-12 08:25 UTC, abaeg commented
> Thank you, this is an interesting solution! Do you think it what we expected?

Thankyou @hasundue !
Most of the cases failed because UI components were missing. Ideally, one would see the expected UI prototype and make changes to fix the layout according. But there was no prototype provided. And considering the time constraint , the quickest way for me was to create the components at runtime.

2022-09-13 00:02 UTC, hasundue requested changes

2022-09-13 00:02 UTC, hasundue commented on .github/workflows/ci.yml
> +        run: deno task dev & deno task start && CHROME_BIN=$(which chrome) deno task test --quiet
This change does violate a rule "without modifying or removing any existing lines in the original code.".
Could you think of a way to avoid it?

2022-09-13 00:06 UTC, hasundue commented
Cool.
You actually "hacked" the problem but I respect that 😄 
Sure, requiring a frontend coding without an UI prototype is kinda awkward as you adressed.

Can we have a casual talk on Zoom?
I'll ask Monami-san to arrange it.

2022-09-13 00:06 UTC, hasundue commented
Cool.
You actually "hacked" the problem but I respect that 😄 
Sure, requiring a frontend coding without an UI prototype is kinda awkward as you adressed.

Can we have a casual talk on Zoom?
I'll ask Monami-san to arrange it.

2022-09-13 08:47 UTC, abaeg commented on .github/workflows/ci.yml
> +        run: deno task dev & deno task start && CHROME_BIN=$(which chrome) deno task test --quiet
You are right. I will move this code change to a separate task and will update the PR.

2022-09-13 08:53 UTC, abaeg commented
> Cool. You actually "hacked" the problem but I respect that smile Sure, requiring a frontend coding without an UI prototype is kinda awkward as you adressed.
> 
> Can we have a casual talk on Zoom? I'll ask Monami-san to arrange it.

Sure, we can do a zoom meeting. I will contact Monami-san via LinkedIn.

2022-09-15 04:46 UTC, hasundue commented on .github/workflows/ci.yml
>        - name: Test
TBH I didn't noticed this solves the problem 😓 
Thanks for the update anyways.

2022-09-15 04:47 UTC, hasundue approved these changes

2022-09-15 04:48 UTC, hasundue commented
ALL GREEN CONFIRMED 😄

2022-09-20 05:12 UTC, hasundue commented
@abaeg Thank you for the meeting.
I should've told about the situation of selection in the first place.
Sorry if you felt uncomfortable with it.

I asked our HR team to setup the final interview with you.
Could you join it if you are still interested in the job?

2022-09-20 08:34 UTC, abaeg commented
> 

It's totally fine @hasundue . I completely understand that you must have found the right talent . Yes, I am interested in the job and will give a final interview as well. But can you kindly confirm whether you are considering any open positions or this interview is a formality?

2022-09-20 10:05 UTC, hasundue commented
The interview is all about the open position for the job you applied.
We do have a candidate who already passed the final interview, but we are holding an offer until screenings for the other candidates who passed the skill test, so that we can contract with the best person for this case.
I'm terribly sorry for my confusing explanation on the meeting.

2022-09-20 11:46 UTC, abaeg commented
> The interview is all about the open position for the job you applied. We do have a candidate who already passed the final interview, but we are holding an offer until screenings are done for the other candidates who passed the skill test, so that we can contract with the best person for this case. I'm terribly sorry for my confusing explanation on the meeting.

Alright, I get it now. Thanks.

2023-07-17 21:08 UTC, closed without merging